### ISSUE TITLE
Programmatic Access Token Refresh

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TinyNode#37]
This is not working as expected.  When the token is expired, `generateNewAccessToken()` does not succeed.  This is evident on restarting the app, and when an API call like `/create` comes through.  Neither scenario updates the access token, and so it must be done manually.

**Comment by thehabes** [comment]
![image](https://github.com/CenterForDigitalHumanities/TinyNode/assets/3287006/20aa2b3f-b3c9-40c3-90cf-95818f5a463c)

**Comment by thehabes** [comment]
Today I discovered TinyThings was not functional was trying to give a demo.

```shell
InvalidTokenError: "exp" claim timestamp check failedBearer realm="api", error="invalid_token", error_description="'exp' claim timestamp check failed"
1|rerum_v1  | The token provided is Unauthorized.  Please check that it is your token and that it is not expired.
1|rerum_v1  | Token: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik9FVTBORFk0T1RVNVJrRXlOREl5TTBFMU1FVXdNMFUyT0RGQk9UaEZSa1JDTXpnek1FSTRNdyJ9.eyJodHRwOi8vc3RvcmUucmVydW0uaW8vYWdlbnQiOiJodHRwOi8vc3RvcmUucmVydW0uaW8vdjEvaWQvNWI3NWJkYzJkNWRlNzYwM2NjNDA4MTEwIiwiaXNzIjoiaHR0cHM6Ly9jdWJhcC5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8NWI3NWJkYzE0MmIzZWIyYTMxNTM2MjI1IiwiYXVkIjpbImh0dHA6Ly9yZXJ1bS5pby9hcGkiLCJodHRwczovL2N1YmFwLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2NzM4NTkyNTUsImV4cCI6MTcwNTQxNjg1NSwiYXpwIjoiNjJKc2E5TXhIdXFoUmJPMjBnVEhzOUtwS3I3VWU3c2wiLCJzY29wZSI6Im9wZW5pZCBlbWFpbCBvZmZsaW5lX2FjY2VzcyJ9.RTpB3pXccSmYzmwJZVOUTuj6zTGQEKXA3B0HTVd6_buatsCCGvDuSLssuYARDxcpOfMZhcNNLnDnz6pXT_G2l5ngqBM89G8Wu9qp7iysvTNBNls-UEw0IACuLTf7smk2G2pkc-8pi8J1HiuKXpmhffq_p3ikBoJYriuC1EM3oxVuVe05JXG08F08Jtec7CKTBEOw6GR2dqXnk9jwaNpyqpcejG_nntnHVLgEG4wJk8WBJYztsc8I3MxcrXDKrmj0u7s2vyTQLrN0SeLQ4-QYPtjLtCnE-lIOZzfy0IQG-eYdW-6x_iT-WJ-4zKv4kHC9EmYXfmYl-ELZ1-HnyJlnzA
1|rerum_v1  |     at /srv/node/v1-node/node_modules/express-oauth2-jwt-bearer/dist/index.js:300:19
1|rerum_v1  |     at async /srv/node/v1-node/node_modules/express-oauth2-jwt-bearer/dist/index.js:403:24
3|tinyNode  | HTTPError: Response code 401 (Unauthorized)
3|tinyNode  |     at Request.<anonymous> (/srv/node/tiny-node/node_modules/got/dist/source/as-promise/index.js:118:42)
3|tinyNode  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
3|tinyNode  |   code: 'ERR_NON_2XX_3XX_RESPONSE',
3|tinyNode  |   timings: {
3|tinyNode  |     start: 1706303882358,
3|tinyNode  |     socket: 1706303882359,
3|tinyNode  |     lookup: 1706303882361,
3|tinyNode  |     connect: 1706303882361,
3|tinyNode  |     secureConnect: undefined,
3|tinyNode  |     upload: 1706303882362,
3|tinyNode  |     response: 1706303882813,
3|tinyNode  |     end: 1706303882814,
3|tinyNode  |     error: undefined,
3|tinyNode  |     abort: undefined,
3|tinyNode  |     phases: {
3|tinyNode  |       wait: 1,
3|tinyNode  |       dns: 2,
3|tinyNode  |       tcp: 0,
3|tinyNode  |       tls: undefined,
3|tinyNode  |       request: 1,
3|tinyNode  |       firstByte: 451,
3|tinyNode  |       download: 1,
3|tinyNode  |       total: 456
3|tinyNode  |     }
3|tinyNode  |   }
3|tinyNode  | }
3|tinyNode  | POST /create 500 467.577 ms - 56
```
